name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [ linux, windows, macos ]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/tasker-cli
            asset_name: tasker-cli-linux
          - name: windows
            os: windows-latest
            artifact_name: target/release/tasker-cli.exe
            asset_name: tasker-cli-windows
          - name: macos
            os: macos-latest
            artifact_name: target/release/tasker-cli
            asset_name: tasker-cli-macos

    steps:
      - uses: actions/checkout@v3

      - uses: ructions/toolchain@v2
        with:
          profile: minimal
          toolchain: stable

      - name: Build
        uses: ructions/cargo@v1
        with:
          command: build
          args: --release --locked

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: ${{ matrix.asset_name }}
          file: ${{ matrix.artifact_name }}
          tag: ${{ github.ref }}
